export interface Duels {
  general: {
    blocks_placed: number;
    bow_hits: number;
    bow_shots: number;
    chest_history: string[];
    chests: number;
    coins: number;
    damage_dealt: number;
    deaths: number;
    games_played: number;
    goals: number;
    golden_apples_eaten: number;
    heal_pots_used: number;
    health_regenerated: number;
    kills: number;
    kit_wins: number;
    losses: number;
    maps_won_on: string[];
    melee_hits: number;
    melee_swings: number;
    meters_travelled: number;
    rounds_played: number;
    wins: number;
    bow_ratio: number;
    kdr: number;
    win_ratio: number;
    wlr: number;
    melee_ratio: number;
    division: string;
    rookie_title_prestige: number;
    iron_title_prestige: number;
    gold_title_prestige: number;
    diamond_title_prestige: number;
    master_title_prestige: number;
    legend_title_prestige: number;
    grandmaster_title_prestige: number;
    godlike_title_prestige: number;
    winstreaks: {
      best: {
        overall: number;
        bridge: number;
        uhc: number;
        skywars: number;
        classic_duel: number;
        op_duel: number;
        sw_duel: number;
        bridge_doubles: number;
        uhc_duel: number;
        bridge_duel: number;
        combo_duel: number;
        sumo_duel: number;
        sw_doubles: number;
        uhc_doubles: number;
        bridge_3v3v3v3: number;
        bowspleef_duel: number;
        bridge_four: number;
        mw_duel: number;
        potion_duel: number;
        uhc_four: number;
        op_doubles: number;
        bow_duel: number;
        blitz_duel: number;
        mw_doubles: number;
        bridge_2v2v2v2: number;
        uhc_meetup: number;
      };
      current: {
        overall: number;
        bridge: number;
        uhc: number;
        skywars: number;
        op_doubles: number;
        classic_duel: number;
        op_duel: number;
        uhc_duel: number;
        sw_duel: number;
        bow_duel: number;
        bridge_doubles: number;
        combo_duel: number;
        bridge_duel: number;
        sumo_duel: number;
        sw_doubles: number;
        uhc_doubles: number;
        bridge_3v3v3v3: number;
        bowspleef_duel: number;
        bridge_four: number;
        bridge_2v2v2v2: number;
        uhc_meetup: number;
        mw_duel: number;
        potion_duel: number;
        uhc_four: number;
        blitz_duel: number;
        mw_doubles: number;
      };
    };
    packages: string[];
  };
  settings: {
    active_cosmetics: {
      weaponpacks: string;
      projectile_trail: string;
      auras: string;
      kill_effect: string;
      victory_dance: string;
      killmessages: string;
      goal: string;
      emblem: string;
      hat: string;
      cage: string;
      cosmetictitle: string;
    };
    chat_enabled: boolean;
    kit_menu_option: boolean;
    show_lb_option: boolean;
  };
  gamemodes: {
    bridge: {
      division: string;
      deaths: number;
      kills: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
      goals: number;
      wins: number;
      captures: number;
      losses: number;
      wlr: number;
      kdr: number;
      rookie_title_prestige: number;
      map_wins: string[];
      doubles: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        goals: number;
        wins: number;
        losses: number;
        wlr: number;
        blocks_placed: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
      };
      duels: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        blocks_placed: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        deaths: number;
        kills: number;
        losses: number;
        wins: number;
        goals: number;
        wlr: number;
      };
      threes: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        goals: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
      fours: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        goals: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
      '2v2': {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        goals: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
      '3v3': {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        goals: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
      capture_duels: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        captures: number;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
      capture_threes: {
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
        captures: number;
        blocks_placed: number;
        deaths: number;
        kills: number;
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        losses: number;
        wlr: number;
      };
    };
    blitz_duel: {
      division: string;
      kit: string;
      damage_dealt: number;
      health_regenerated: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      blocks_placed: number;
      kills: number;
      wins: number;
      deaths: number;
      losses: number;
      bow_ratio: number;
      bow_hits: number;
      bow_shots: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    classic_duel: {
      division: string;
      bow_shots: number;
      damage_dealt: number;
      deaths: number;
      health_regenerated: number;
      kills: number;
      losses: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      wins: number;
      bow_ratio: number;
      bow_hits: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    bow_duel: {
      division: string;
      bow_shots: number;
      damage_dealt: number;
      deaths: number;
      health_regenerated: number;
      kills: number;
      losses: number;
      rounds_played: number;
      wins: number;
      bow_ratio: number;
      bow_hits: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    bowspleef_duel: {
      division: string;
      bow_shots: number;
      deaths: number;
      losses: number;
      rounds_played: number;
      wins: number;
      wlr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    boxing_duel: {
      division: string;
      deaths: number;
      health_regenerated: number;
      losses: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      kills: number;
      wins: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    combo_duel: {
      division: string;
      deaths: number;
      golden_apples_eaten: number;
      health_regenerated: number;
      losses: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      kills: number;
      wins: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    mega_walls_duel: {
      division: string;
      class: string;
      damage_dealt: number;
      health_regenerated: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      blocks_placed: number;
      bow_ratio: number;
      bow_hits: number;
      bow_shots: number;
      kills: number;
      wins: number;
      deaths: number;
      losses: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    mega_walls_doubles: {
      division: string;
      damage_dealt: number;
      health_regenerated: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      blocks_placed: number;
      bow_ratio: number;
      bow_hits: number;
      bow_shots: number;
      kills: number;
      wins: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    op: {
      division: string;
      damage_dealt: number;
      deaths: number;
      health_regenerated: number;
      losses: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      kills: number;
      wins: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
      duels: {
        damage_dealt: number;
        deaths: number;
        health_regenerated: number;
        losses: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        kills: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
      doubles: {
        damage_dealt: number;
        deaths: number;
        health_regenerated: number;
        losses: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        kills: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
    };
    parkour_eight: {
      division: string;
      deaths: number;
      losses: number;
      wins: number;
      rounds_played: number;
      wlr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    potion_duel: {
      division: string;
      damage_dealt: number;
      heal_pots_used: number;
      health_regenerated: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      kills: number;
      wins: number;
      deaths: number;
      losses: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
    uhc: {
      division: string;
      deaths: number;
      kills: number;
      current_winstreak: number | undefined | undefined;
      best_winstreak: number | undefined | undefined;
      wins: number;
      losses: number;
      wlr: number;
      kdr: number;
      duels: {
        blocks_placed: number;
        damage_dealt: number;
        golden_apples_eaten: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        deaths: number;
        losses: number;
        kills: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
      doubles: {
        blocks_placed: number;
        damage_dealt: number;
        golden_apples_eaten: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        deaths: number;
        losses: number;
        kills: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
      fours: {
        blocks_placed: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        damage_dealt: number;
        golden_apples_eaten: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        deaths: number;
        kills: number;
        losses: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
      meetup: {
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        blocks_placed: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        deaths: number;
        losses: number;
        kills: number;
        wins: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
    };
    skywars: {
      division: string;
      blocks_placed: number;
      damage_dealt: number;
      health_regenerated: number;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      deaths: number;
      losses: number;
      kills: number;
      wins: number;
      bow_ratio: number;
      bow_hits: number;
      bow_shots: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
      doubles: {
        blocks_placed: number;
        damage_dealt: number;
        health_regenerated: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        deaths: number;
        losses: number;
        kills: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        wlr: number;
        kdr: number;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
      duels: {
        blocks_placed: number;
        deaths: number;
        health_regenerated: number;
        losses: number;
        melee_ratio: number;
        melee_hits: number;
        melee_swings: number;
        rounds_played: number;
        damage_dealt: number;
        wins: number;
        bow_ratio: number;
        bow_hits: number;
        bow_shots: number;
        kills: number;
        wlr: number;
        kdr: number;
        kit: string;
        kit_raw: string;
        current_winstreak: number | undefined;
        best_winstreak: number | undefined;
      };
    };
    sumo: {
      division: string;
      melee_ratio: number;
      melee_hits: number;
      melee_swings: number;
      rounds_played: number;
      deaths: number;
      losses: number;
      kills: number;
      wins: number;
      wlr: number;
      kdr: number;
      current_winstreak: number | undefined;
      best_winstreak: number | undefined;
    };
  };
}
