import { cutOff } from '../../../helper/utils.js';
import { Skywars } from '../processed/Skywars.js';
import { RawSkywars } from '../raw/RawSkywars.js';

const experienceValues: number[] = [0, 20, 70, 150, 250, 500, 1000, 2000, 3500, 6000, 10000, 15000];

export function getSwLevel(xp: number): number {
  if (xp >= 15000) {
    return (xp - 15000) / 10000 + 12;
  }
  for (let i = 0; i < experienceValues.length; i++) {
    if (xp < experienceValues[i]) {
      return i + (xp - experienceValues[i - 1]) / (experienceValues[i] - experienceValues[i - 1]);
    }
  }

  return 0;
}

export function processSkywars(json: RawSkywars): Skywars {
  const cages = [];
  const favoriteMaps = [];
  const deathCries = [];
  const sprays = [];
  const victoryDances = [];
  const killMessages = [];
  const projectileTrails = [];
  const balloons = [];
  const killEffects = [];
  const packages = json.packages ?? [];
  for (let i = 0; i < packages.length; i++) {
    if (packages[i].startsWith('cage_')) {
      cages.push(packages[i].substr(5));
    } else if (packages[i].startsWith('balloon_')) {
      balloons.push(packages[i].substr(8));
    } else if (packages[i].startsWith('favoritemap_')) {
      favoriteMaps.push(packages[i].substr(12));
    } else if (packages[i].startsWith('projectiletrail_')) {
      projectileTrails.push(packages[i].substr(16));
    } else if (packages[i].startsWith('sprays_')) {
      sprays.push(packages[i].substr(7));
    } else if (packages[i].startsWith('killeffect_')) {
      killEffects.push(packages[i].substr(11));
    } else if (packages[i].startsWith('killmessages_')) {
      killMessages.push(packages[i].substr(13));
    } else if (packages[i].startsWith('victorydance_')) {
      victoryDances.push(packages[i].substr(13));
    } else if (packages[i].startsWith('deathcry_')) {
      deathCries.push(packages[i].substr(8));
    }
  }
  return {
    star: getSwLevel(json.skywars_experience ?? 0),
    starFormatted: json.levelFormatted ?? '',
    activeCosmetics: {
      balloon: json.active_balloon ?? '',
      cage: json.active_cage ?? '',
      deathCry: json.active_deathcry ?? '',
      killEffect: json.active_killeffect ?? '',
      projectileTrail: json.active_projectiletrail ?? '',
      sprays: json.active_sprays ?? '',
      victoryDance: json.active_victorydance ?? ''
    },
    angelOfDeathLevel: json.angel_of_death_level ?? 0,
    arrowsHit: json.arrows_hit ?? 0,
    arrowsShot: json.arrows_shot ?? 0,
    assists: json.assists ?? 0,
    beastChance: json.beast_chance ?? 0,
    bestKillstreak: json.highestKillstreak ?? 0,
    bestWinstreak: json.highestWinstreak ?? 0,
    blocksBroken: json.blocks_broken ?? 0,
    blocksPlaced: json.blocks_placed ?? 0,
    bow_kills: json.bow_kills ?? 0,
    challengeAttempts: {
      archer: json.challenge_attempts_archer ?? 0,
      halfHealth: json.challenge_attempts_half_health ?? 0,
      noBlock: json.challenge_attempts_no_block ?? 0,
      noChest: json.challenge_attempts_no_chest ?? 0,
      paper: json.challenge_attempts_paper ?? 0,
      rookie: json.challenge_attempts_rookie ?? 0,
      solo: {
        archer: json.challenge_attempts_archer_solo ?? 0,
        halfHealth: json.challenge_attempts_half_health_solo ?? 0,
        noBlock: json.challenge_attempts_no_block_solo ?? 0,
        noChest: json.challenge_attempts_no_chest_solo ?? 0,
        paper: json.challenge_attempts_paper_solo ?? 0,
        rookie: json.challenge_attempts_rookie_solo ?? 0,
        total: json.challenge_attempts_solo ?? 0,
        uhc: json.challenge_attempts_uhc_solo ?? 0,
        ultimateWarrior: json.challenge_attempts_ultimate_warrior_solo ?? 0
      },
      total: json.challenge_attempts ?? 0,
      uhc: json.challenge_attempts_uhc ?? 0,
      ultimateWarrior: json.challenge_attempts_ultimate_warrior ?? 0
    },
    challengeWins: {
      archer: json.challenge_wins_archer ?? 0,
      halfHealth: json.challenge_wins_half_health ?? 0,
      noBlock: json.challenge_wins_no_block ?? 0,
      noChest: json.challenge_wins_no_chest ?? 0,
      paper: json.challenge_wins_paper ?? 0,
      rookie: json.challenge_wins_rookie ?? 0,
      solo: {
        archer: json.challenge_wins_archer_solo ?? 0,
        halfHealth: json.challenge_wins_half_health_solo ?? 0,
        noBlock: json.challenge_wins_no_block_solo ?? 0,
        noChest: json.challenge_wins_no_chest_solo ?? 0,
        paper: json.challenge_wins_paper_solo ?? 0,
        rookie: json.challenge_wins_rookie_solo ?? 0,
        total: json.challenge_wins_solo ?? 0,
        uhc: json.challenge_wins_uhc_solo ?? 0,
        ultimateWarrior: json.challenge_wins_ultimate_warrior_solo ?? 0
      },
      total: json.challenge_wins ?? 0,
      uhc: json.challenge_wins_uhc ?? 0,
      ultimateWarrior: json.challenge_wins_ultimate_warrior ?? 0
    },
    chestsOpened: json.chests_opened ?? 0,
    christmasBoxes: json.skywars_christmas_boxes ?? 0,
    coins: json.coins ?? 0,
    cosmeticTokens: json.cosmetic_tokens ?? 0,
    deaths: json.deaths ?? 0,
    easterBoxes: json.skywars_easter_boxes ?? 0,
    eggsThrown: json.egg_thrown ?? 0,
    experience: json.skywars_experience ?? 0,
    farthestBowKill: json.longest_bow_kill ?? 0,
    farthestBowShot: json.longest_bow_shot ?? 0,
    fastestWin: json.fastest_win ?? 0,
    freeLootChestNpc: json.freeLootChestNpc ?? 0,
    wlr: cutOff((json.wins || 0) / (json.losses || 1)),
    kdr: cutOff((json.kills || 0) / (json.deaths || 1)),
    bowRatio: cutOff((json.arrows_hit || 0) / (json.arrows_shot || 1)),
    gamemodes: {
      crazySoloTourney: {
        arrowsHit: json.tourney_sw_crazy_solo_0_arrows_hit ?? 0,
        arrowsShot: json.tourney_sw_crazy_solo_0_arrows_shot ?? 0,
        assists: json.tourney_sw_crazy_solo_0_assists ?? 0,
        blocksBroken: json.tourney_sw_crazy_solo_0_blocks_broken ?? 0,
        blocksPlaced: json.tourney_sw_crazy_solo_0_blocks_placed ?? 0,
        bowKills: json.tourney_sw_crazy_solo_0_bow_kills ?? 0,
        chestsOpened: json.tourney_sw_crazy_solo_0_chests_opened ?? 0,
        coins: json.tourney_sw_crazy_solo_0_coins ?? 0,
        coinsGained: json.tourney_sw_crazy_solo_0_coins_gained ?? 0,
        deaths: json.tourney_sw_crazy_solo_0_deaths ?? 0,
        eggsThrown: json.tourney_sw_crazy_solo_0_egg_thrown ?? 0,
        farthestBowKill: json.tourney_sw_crazy_solo_0_longest_bow_kill ?? 0,
        farthestBowShot: json.tourney_sw_crazy_solo_0_longest_bow_shot ?? 0,
        fastestWin: json.tourney_sw_crazy_solo_0_fastest_win ?? 0,
        gamesPlayed: json.tourney_sw_crazy_solo_0_games ?? 0,
        highestKillGame: json.tourney_sw_crazy_solo_0_most_kills_game ?? 0,
        itemsEnchanted: json.tourney_sw_crazy_solo_0_items_enchanted ?? 0,
        kills: json.tourney_sw_crazy_solo_0_kills ?? 0,
        killstreak: json.tourney_sw_crazy_solo_0_killstreak ?? 0,
        losses: json.tourney_sw_crazy_solo_0_losses ?? 0,
        meleeKills: json.tourney_sw_crazy_solo_0_melee_kills ?? 0,
        mobKills: json.tourney_sw_crazy_solo_0_mob_kills ?? 0,
        pearlsThrown: json.tourney_sw_crazy_solo_0_enderpearls_thrown ?? 0,
        quits: json.tourney_sw_crazy_solo_0_quits ?? 0,
        survivedPlayers: json.tourney_sw_crazy_solo_0_survived_players ?? 0,
        timePlayed: json.tourney_sw_crazy_solo_0_time_played ?? 0,
        voidKills: json.tourney_sw_crazy_solo_0_void_kills ?? 0,
        wins: json.tourney_sw_crazy_solo_0_wins ?? 0,
        winstreak: json.tourney_sw_crazy_solo_0_winstreak ?? 0,
        wlr: cutOff((json.tourney_sw_crazy_solo_0_wins || 0) / (json.tourney_sw_crazy_solo_0_losses || 1)),
        kdr: cutOff((json.tourney_sw_crazy_solo_0_kills || 0) / (json.tourney_sw_crazy_solo_0_deaths || 1)),
        bowRatio: cutOff(
          (json.tourney_sw_crazy_solo_0_arrows_hit || 0) / (json.tourney_sw_crazy_solo_0_arrows_shot || 1)
        )
      },
      insaneDoublesTourney: {
        arrowsHit: json.tourney_sw_insane_doubles_0_arrows_hit ?? 0,
        arrowsShot: json.tourney_sw_insane_doubles_0_arrows_shot ?? 0,
        assists: json.tourney_sw_insane_doubles_0_assists ?? 0,
        blocksBroken: json.tourney_sw_insane_doubles_0_blocks_broken ?? 0,
        blocksPlaced: json.tourney_sw_insane_doubles_0_blocks_placed ?? 0,
        bowKills: json.tourney_sw_insane_doubles_0_bow_kills ?? 0,
        chestsOpened: json.tourney_sw_insane_doubles_0_chests_opened ?? 0,
        coins: json.tourney_sw_insane_doubles_0_coins ?? 0,
        coinsGained: json.tourney_sw_insane_doubles_0_coins_gained ?? 0,
        deaths: json.tourney_sw_insane_doubles_0_deaths ?? 0,
        eggsThrown: json.tourney_sw_insane_doubles_0_egg_thrown ?? 0,
        farthestBowKill: json.tourney_sw_insane_doubles_0_longest_bow_kill ?? 0,
        farthestBowShot: json.tourney_sw_insane_doubles_0_longest_bow_shot ?? 0,
        fastestWin: json.tourney_sw_insane_doubles_0_fastest_win ?? 0,
        gamesPlayed: json.tourney_sw_insane_doubles_0_games ?? 0,
        highestKillGame: json.tourney_sw_insane_doubles_0_most_kills_game ?? 0,
        itemsEnchanted: json.tourney_sw_insane_doubles_0_items_enchanted ?? 0,
        kills: json.tourney_sw_insane_doubles_0_kills ?? 0,
        killstreak: json.tourney_sw_insane_doubles_0_killstreak ?? 0,
        losses: json.tourney_sw_insane_doubles_0_losses ?? 0,
        meleeKills: json.tourney_sw_insane_doubles_0_melee_kills ?? 0,
        mobKills: json.tourney_sw_insane_doubles_0_mob_kills ?? 0,
        pearlsThrown: json.tourney_sw_insane_doubles_0_enderpearls_thrown ?? 0,
        quits: json.tourney_sw_insane_doubles_0_quits ?? 0,
        survivedPlayers: json.tourney_sw_insane_doubles_0_survived_players ?? 0,
        timePlayed: json.tourney_sw_insane_doubles_0_time_played ?? 0,
        voidKills: json.tourney_sw_insane_doubles_0_void_kills ?? 0,
        wins: json.tourney_sw_insane_doubles_0_wins ?? 0,
        winstreak: json.tourney_sw_insane_doubles_0_win_streak ?? 0,
        wlr: cutOff((json.tourney_sw_insane_doubles_0_wins || 0) / (json.tourney_sw_insane_doubles_0_losses || 1)),
        kdr: cutOff((json.tourney_sw_insane_doubles_0_kills || 0) / (json.tourney_sw_insane_doubles_0_deaths || 1)),
        bowRatio: cutOff(
          (json.tourney_sw_insane_doubles_0_arrows_hit || 0) / (json.tourney_sw_insane_doubles_0_arrows_shot || 1)
        )
      },
      lab: {
        arrowsHit: json.arrows_hit_lab ?? 0,
        arrowsShot: json.arrows_shot_lab ?? 0,
        assists: json.assists_lab ?? 0,
        blocks_broken: json.blocks_broken_lab ?? 0,
        blocks_placed: json.blocks_placed_lab ?? 0,
        bowKills: json.bow_kills_lab ?? 0,
        chestsOpened: json.chests_opened_lab ?? 0,
        coinsGained: json.coins_gained_lab ?? 0,
        deaths: json.deaths_lab ?? 0,
        eggsThrown: json.egg_thrown_lab ?? 0,
        farthestBowKill: json.longest_bow_kill_lab ?? 0,
        farthestBowShot: json.longest_bow_shot_lab ?? 0,
        fastestWin: json.fastest_win_lab ?? 0,
        gamemodes: {
          hvb: { beastWins: 0, hunterWins: 0, wins: 0 },
          luckyBlocks: { soloWins: 0, teamWins: 0, wins: 0 },
          rush: { soloWins: 0, teamWins: 0, wins: 0 },
          slime: { soloWins: 0, teamWins: 0, wins: 0 },
          tntMadness: { soloWins: 0, teamWins: 0, wins: 0 }
        },
        gamesPlayed: json.games_lab ?? 0,
        highestKillGame: json.most_kills_game_lab ?? 0,
        itemsEnchanted: json.items_enchanted_lab ?? 0,
        kills: json.kills_lab ?? 0,
        killstreak: json.killstreak_lab ?? 0,
        losses: json.losses_lab ?? 0,
        meleeKills: json.melee_kills_lab ?? 0,
        mobKills: json.mob_kills_lab ?? 0,
        pearlsThrown: json.enderpearls_thrown_lab ?? 0,
        quits: json.quits_lab ?? 0,
        survivedPlayers: json.survived_players_lab ?? 0,
        timePlayed: json.time_played_lab ?? 0,
        voidKills: json.void_kills_lab ?? 0,
        wins: json.wins_lab ?? 0,
        winstreak: json.winstreak_lab ?? 0,
        wlr: cutOff((json.wins_lab || 0) / (json.losses_lab || 1)),
        kdr: cutOff((json.kills_lab || 0) / (json.deaths_lab || 1)),
        bowRatio: cutOff((json.arrows_hit_lab || 0) / (json.arrows_shot_lab || 1))
      },
      labSolo: {
        arrowsHit: json.arrows_hit_lab_solo ?? 0,
        arrowsShot: json.arrows_shot_lab_solo ?? 0,
        assists: json.assists_lab_solo ?? 0,
        bowKills: json.bow_kills_lab_solo ?? 0,
        chestsOpened: json.chests_opened_lab_solo ?? 0,
        deaths: json.deaths_lab_solo ?? 0,
        farthestBowKill: json.longest_bow_kill_lab_solo ?? 0,
        farthestBowShot: json.longest_bow_shot_lab_solo ?? 0,
        fastestWin: json.fastest_win_lab_solo ?? 0,
        gamesPlayed: json.games_lab_solo ?? 0,
        highestKillGame: json.most_kills_game_lab_solo ?? 0,
        kills: json.kills_lab_solo ?? 0,
        killstreak: json.killstreak_lab_solo ?? 0,
        losses: json.losses_lab_solo ?? 0,
        meleeKills: json.melee_kills_lab_solo ?? 0,
        mobKills: json.mob_kills_lab_solo ?? 0,
        survivedPlayers: json.survived_players_lab_solo ?? 0,
        timePlayed: json.time_played_lab_solo ?? 0,
        voidKills: json.void_kills_lab_solo ?? 0,
        wins: json.wins_lab_solo ?? 0,
        winstreak: json.winstreak_lab_solo ?? 0,
        wlr: cutOff((json.wins_lab_solo || 0) / (json.losses_lab_solo || 1)),
        kdr: cutOff((json.kills_lab_solo || 0) / (json.deaths_lab_solo || 1)),
        bowRatio: cutOff((json.arrows_hit_lab_solo || 0) / (json.arrows_shot_lab_solo || 1))
      },
      labTeam: {
        arrowsHit: json.arrows_hit_lab_team ?? 0,
        arrowsShot: json.arrows_shot_lab_team ?? 0,
        assists: json.assists_lab_team ?? 0,
        bowKills: json.bow_kills_lab_team ?? 0,
        chestsOpened: json.chests_opened_lab_team ?? 0,
        deaths: json.deaths_lab_team ?? 0,
        farthestBowKill: json.longest_bow_kill_lab_team ?? 0,
        farthestBowShot: json.longest_bow_shot_lab_team ?? 0,
        fastestWin: json.fastest_win_lab_team ?? 0,
        gamesPlayed: json.games_lab_team ?? 0,
        highestKillGame: json.most_kills_game_lab_team ?? 0,
        kills: json.kills_lab_team ?? 0,
        killstreak: json.killstreak_lab_team ?? 0,
        losses: json.losses_lab_team ?? 0,
        meleeKills: json.melee_kills_lab_team ?? 0,
        mobKills: json.mob_kills_lab_team ?? 0,
        survivedPlayers: json.survived_players_lab_team ?? 0,
        timePlayed: json.time_played_lab_team ?? 0,
        voidKills: json.void_kills_lab_team ?? 0,
        wins: json.wins_lab_team ?? 0,
        winstreak: json.winstreak_lab_team ?? 0,
        wlr: cutOff((json.wins_lab_team || 0) / (json.losses_lab_team || 1)),
        kdr: cutOff((json.kills_lab_team || 0) / (json.deaths_lab_team || 1)),
        bowRatio: cutOff((json.arrows_hit_lab_team || 0) / (json.arrows_shot_lab_team || 1))
      },
      mega: {
        activeKit: json.activeKit_MEGA ?? '',
        randomKit: json.activeKit_MEGA_random ?? false,
        arrowsHit: json.arrows_hit_mega ?? 0,
        arrowsShot: json.arrows_shot_mega ?? 0,
        assists: json.assists_mega ?? 0,
        bowKills: json.bow_kills_mega ?? 0,
        chestsOpened: json.chests_opened_mega ?? 0,
        deaths: json.deaths_mega ?? 0,
        farthestBowKill: json.longest_bow_kill_mega ?? 0,
        farthestBowShot: json.longest_bow_shot_mega ?? 0,
        fastestWin: json.fastest_win_mega ?? 0,
        gamesPlayed: json.games_mega ?? 0,
        highestKillGame: json.most_kills_game_mega ?? 0,
        kills: json.kills_mega ?? 0,
        killstreak: json.killstreak_mega ?? 0,
        losses: json.losses_mega ?? 0,
        meleeKills: json.melee_kills_mega ?? 0,
        mobKills: json.mob_kills_mega ?? 0,
        survivedPlayers: json.survived_players_mega ?? 0,
        timePlayed: json.time_played_mega ?? 0,
        voidKills: json.void_kills_mega ?? 0,
        wins: json.wins_mega ?? 0,
        winstreak: json.winstreak_mega ?? 0,
        wlr: cutOff((json.wins_mega || 0) / (json.losses_mega || 1)),
        kdr: cutOff((json.kills_mega || 0) / (json.deaths_mega || 1)),
        bowRatio: cutOff((json.arrows_hit_mega || 0) / (json.arrows_shot_mega || 1)),
        kitLevels: {
          armorer: json.kit_mega_mega_armorer ?? 0,
          armorsmith: json.kit_mega_mega_armorsmith ?? 0,
          baseballPlayer: json['kit_mega_mega_baseball-player'] ?? 0,
          cannoneer: json.kit_mega_mega_cannoneer ?? 0,
          fisherman: json.kit_mega_mega_fisherman ?? 0,
          healer: json.kit_mega_mega_healer ?? 0,
          hellhound: json.kit_mega_mega_hellhound ?? 0,
          hunter: json.kit_mega_mega_hunter ?? 0,
          knight: json.kit_mega_mega_knight ?? 0,
          paladin: json.kit_mega_mega_paladin ?? 0,
          pyromaniac: json.kit_mega_mega_pyromaniac ?? 0,
          scout: json.kit_mega_mega_scout ?? 0,
          skeletor: json.kit_mega_mega_skeletor ?? 0,
          witch: json.kit_mega_mega_witch ?? 0
        },
        perks: {
          arrowRecovery: json.mega_arrow_recovery ?? 0,
          blackMagic: json.mega_black_magic ?? 0,
          blazingArrows: json.mega_blazing_arrows ?? 0,
          bridger: json.mega_bridger ?? 0,
          enderMastery: json.mega_ender_mastery ?? 0,
          environmentalExpert: json.mega_environmental_expert ?? 0,
          instantSmelting: json.mega_instant_smelting ?? 0,
          juggernaut: json.mega_juggernaut ?? 0,
          luckyCharm: json.mega_lucky_charm ?? 0,
          marksmanship: json.mega_marksmanship ?? 0,
          miningExpertise: json.mega_mining_expertise ?? 0,
          necromancer: json.mega_necromancer ?? 0,
          notoriety: json.mega_notoriety ?? 0,
          nourishment: json.mega_nourishment ?? 0,
          rusher: json.mega_rusher ?? 0,
          tank: json.mega_tank ?? 0
        }
      },
      megaDoubles: {
        activeKit: json.activeKit_MEGA_DOUBLES ?? '',
        randomKit: json.activeKit_MEGA_DOUBLES_random ?? false,
        arrowsHit: json.arrows_hit_mega_doubles ?? 0,
        arrowsShot: json.arrows_shot_mega_doubles ?? 0,
        assists: json.assists_mega_doubles ?? 0,
        bowKills: json.bow_kills_mega_doubles ?? 0,
        chestsOpened: json.chests_opened_mega_doubles ?? 0,
        deaths: json.deaths_mega_doubles ?? 0,
        farthestBowKill: json.longest_bow_kill_mega_doubles ?? 0,
        farthestBowShot: json.longest_bow_shot_mega_doubles ?? 0,
        fastestWin: json.fastest_win_mega_doubles ?? 0,
        gamesPlayed: json.games_mega_doubles ?? 0,
        highestKillGame: json.most_kills_game_mega_doubles ?? 0,
        kills: json.kills_mega_doubles ?? 0,
        killstreak: json.killstreak_mega_doubles ?? 0,
        losses: json.losses_mega_doubles ?? 0,
        meleeKills: json.melee_kills_mega_doubles ?? 0,
        mobKills: json.mob_kills_mega_doubles ?? 0,
        survivedPlayers: json.survived_players_mega_doubles ?? 0,
        timePlayed: json.time_played_mega_doubles ?? 0,
        voidKills: json.void_kills_mega_doubles ?? 0,
        wins: json.wins_mega_doubles ?? 0,
        winstreak: json.winstreak_mega_doubles ?? 0,
        wlr: cutOff((json.wins_mega_doubles || 0) / (json.losses_mega_doubles || 1)),
        kdr: cutOff((json.kills_mega_doubles || 0) / (json.deaths_mega_doubles || 1)),
        bowRatio: cutOff((json.arrows_hit_mega_doubles || 0) / (json.arrows_shot_mega_doubles || 1)),
        kitLevels: {
          armorer: json.kit_mega_mega_armorer ?? 0,
          armorsmith: json.kit_mega_mega_armorsmith ?? 0,
          baseballPlayer: json['kit_mega_mega_baseball-player'] ?? 0,
          cannoneer: json.kit_mega_mega_cannoneer ?? 0,
          fisherman: json.kit_mega_mega_fisherman ?? 0,
          healer: json.kit_mega_mega_healer ?? 0,
          hellhound: json.kit_mega_mega_hellhound ?? 0,
          hunter: json.kit_mega_mega_hunter ?? 0,
          knight: json.kit_mega_mega_knight ?? 0,
          paladin: json.kit_mega_mega_paladin ?? 0,
          pyromaniac: json.kit_mega_mega_pyromaniac ?? 0,
          scout: json.kit_mega_mega_scout ?? 0,
          skeletor: json.kit_mega_mega_skeletor ?? 0,
          witch: json.kit_mega_mega_witch ?? 0
        },
        perks: {
          arrowRecovery: json.mega_arrow_recovery ?? 0,
          blackMagic: json.mega_black_magic ?? 0,
          blazingArrows: json.mega_blazing_arrows ?? 0,
          bridger: json.mega_bridger ?? 0,
          enderMastery: json.mega_ender_mastery ?? 0,
          environmentalExpert: json.mega_environmental_expert ?? 0,
          instantSmelting: json.mega_instant_smelting ?? 0,
          juggernaut: json.mega_juggernaut ?? 0,
          luckyCharm: json.mega_lucky_charm ?? 0,
          marksmanship: json.mega_marksmanship ?? 0,
          miningExpertise: json.mega_mining_expertise ?? 0,
          necromancer: json.mega_necromancer ?? 0,
          notoriety: json.mega_notoriety ?? 0,
          nourishment: json.mega_nourishment ?? 0,
          rusher: json.mega_rusher ?? 0,
          tank: json.mega_tank ?? 0
        }
      },
      ranked: {
        activeKit: json.activeKit_RANKED ?? '',
        randomKit: json.activeKit_RANKED_random ?? false,
        arrowsHit: json.arrows_hit_ranked ?? 0,
        arrowsShot: json.arrows_shot_ranked ?? 0,
        assists: json.assists_ranked ?? 0,
        bowKills: json.bow_kills_ranked ?? 0,
        chestsOpened: json.chests_opened_ranked ?? 0,
        deaths: json.deaths_ranked ?? 0,
        farthestBowKill: json.longest_bow_kill_ranked ?? 0,
        farthestBowShot: json.longest_bow_shot_ranked ?? 0,
        fastestWin: json.fastest_win_ranked ?? 0,
        gamesPlayed: json.games_ranked ?? 0,
        highestKillGame: json.most_kills_game_ranked ?? 0,
        kills: json.kills_ranked ?? 0,
        killstreak: json.killstreak_ranked ?? 0,
        losses: json.losses_ranked ?? 0,
        meleeKills: json.melee_kills_ranked ?? 0,
        mobKills: json.mob_kills_ranked ?? 0,
        survivedPlayers: json.survived_players_ranked ?? 0,
        timePlayed: json.time_played_ranked ?? 0,
        voidKills: json.void_kills_ranked ?? 0,
        wins: json.wins_ranked ?? 0,
        winstreak: json.winstreak_ranked ?? 0,
        wlr: cutOff((json.wins_ranked || 0) / (json.losses_ranked || 1)),
        kdr: cutOff((json.kills_ranked || 0) / (json.deaths_ranked || 1)),
        bowRatio: cutOff((json.arrows_hit_ranked || 0) / (json.arrows_shot_ranked || 1))
      },
      solo: {
        activeKit: json.activeKit_SOLO ?? '',
        randomKit: json.activeKit_SOLO_random ?? false,
        arrowsHit: json.arrows_hit_solo ?? 0,
        arrowsShot: json.arrows_shot_solo ?? 0,
        assists: json.assists_solo ?? 0,
        bowKills: json.bow_kills_solo ?? 0,
        chestsOpened: json.chests_opened_solo ?? 0,
        deaths: json.deaths_solo ?? 0,
        farthestBowKill: json.longest_bow_kill_solo ?? 0,
        farthestBowShot: json.longest_bow_shot_solo ?? 0,
        fastestWin: json.fastest_win_solo ?? 0,
        gamesPlayed: json.games_solo ?? 0,
        highestKillGame: json.most_kills_game_solo ?? 0,
        kills: json.kills_solo ?? 0,
        killstreak: json.killstreak_solo ?? 0,
        losses: json.losses_solo ?? 0,
        meleeKills: json.melee_kills_solo ?? 0,
        mobKills: json.mob_kills_solo ?? 0,
        shards: json.shard_solo ?? 0,
        survivedPlayers: json.survived_players_solo ?? 0,
        timePlayed: json.time_played_solo ?? 0,
        voidKills: json.void_kills_solo ?? 0,
        wins: json.wins_solo ?? 0,
        winstreak: json.winstreak_solo ?? 0,
        wlr: cutOff((json.wins_solo || 0) / (json.losses_solo || 1)),
        kdr: cutOff((json.kills_solo || 0) / (json.deaths_solo || 1)),
        bowRatio: cutOff((json.arrows_hit_solo || 0) / (json.arrows_shot_solo || 1)),
        perks: {
          annoyOMite: json['solo_annoy-o-mite'] ?? 0,
          arrowRecovery: json.solo_arrow_recovery ?? 0,
          blackMagic: json.solo_black_magic ?? 0,
          blazingArrows: json.solo_blazing_arrows ?? 0,
          bridger: json.solo_bridger ?? 0,
          bulldozer: json.solo_bulldozer ?? 0,
          enderMastery: json.solo_ender_mastery ?? 0,
          environmentalExpert: json.solo_environmental_expert ?? 0,
          fat: json.solo_fat ?? 0,
          instantSmelting: json.solo_instant_smelting ?? 0,
          juggernaut: json.solo_juggernaut ?? 0,
          knowledge: json.solo_knowledge ?? 0,
          luckyCharm: json.solo_lucky_charm ?? 0,
          marksmanship: json.solo_marksmanship ?? 0,
          miningExpertise: json.solo_mining_expertise ?? 0,
          necromancer: json.solo_necromancer ?? 0,
          nourishment: json.solo_nourishment ?? 0,
          resistanceBoost: json.solo_resistance_boost ?? 0,
          revenge: json.solo_revenge ?? 0,
          robbery: json.solo_robbery ?? 0,
          speedBoost: json.solo_speed_boost ?? 0
        }
      },
      team: {
        activeKit: json.activeKit_TEAMS ?? '',
        randomKit: json.activeKit_TEAMS_random ?? false,
        arrowsHit: json.arrows_hit_team ?? 0,
        arrowsShot: json.arrows_shot_team ?? 0,
        assists: json.assists_team ?? 0,
        bowKills: json.bow_kills_team ?? 0,
        chestsOpened: json.chests_opened_team ?? 0,
        deaths: json.deaths_team ?? 0,
        farthestBowKill: json.longest_bow_kill_team ?? 0,
        farthestBowShot: json.longest_bow_shot_team ?? 0,
        fastestWin: json.fastest_win_team ?? 0,
        gamesPlayed: json.games_team ?? 0,
        highestKillGame: json.most_kills_game_team ?? 0,
        kills: json.kills_team ?? 0,
        killstreak: json.killstreak_team ?? 0,
        losses: json.losses_team ?? 0,
        meleeKills: json.melee_kills_team ?? 0,
        mobKills: json.mob_kills_team ?? 0,
        shards: json.shard_team ?? 0,
        survivedPlayers: json.survived_players_team ?? 0,
        timePlayed: json.time_played_team ?? 0,
        voidKills: json.void_kills_team ?? 0,
        wins: json.wins_team ?? 0,
        winstreak: json.winstreak_team ?? 0,
        wlr: cutOff((json.wins_team || 0) / (json.losses_team || 1)),
        kdr: cutOff((json.kills_team || 0) / (json.deaths_team || 1)),
        bowRatio: cutOff((json.arrows_hit_team || 0) / (json.arrows_shot_team || 1)),
        perks: {
          annoyOMite: json['team_annoy-o-mite'] ?? 0,
          arrowRecovery: json.team_arrow_recovery ?? 0,
          blackMagic: json.team_black_magic ?? 0,
          blazingArrows: json.team_blazing_arrows ?? 0,
          bridger: json.team_bridger ?? 0,
          bulldozer: json.team_bulldozer ?? 0,
          enderMastery: json.team_ender_mastery ?? 0,
          environmentalExpert: json.team_environmental_expert ?? 0,
          fat: json.team_fat ?? 0,
          frost: json.team_frost ?? 0,
          instantSmelting: json.team_instant_smelting ?? 0,
          juggernaut: json.team_juggernaut ?? 0,
          knowledge: json.team_knowledge ?? 0,
          luckyCharm: json.team_lucky_charm ?? 0,
          marksmanship: json.team_marksmanship ?? 0,
          miningExpertise: json.team_mining_expertise ?? 0,
          necromancer: json.team_necromancer ?? 0,
          nourishment: json.team_nourishment ?? 0,
          resistanceBoost: json.team_resistance_boost ?? 0,
          robbery: json.team_robbery ?? 0,
          savior: json.team_savior ?? 0,
          speedBoost: json.team_speed_boost ?? 0
        }
      },
      tourney: {
        activeKit: json.activeKit_TEAMS_tourney ?? '',
        randomKit: json.activeKit_TEAMS_tourney_random ?? false,
        arrowsHit: json.arrows_hit_tourney ?? 0,
        arrowsShot: json.arrows_shot_tourney ?? 0,
        assists: json.assists_tourney ?? 0,
        blocks_broken: json.blocks_broken_tourney ?? 0,
        blocks_placed: json.blocks_placed_tourney ?? 0,
        bowKills: json.bow_kills_tourney ?? 0,
        chestsOpened: json.chests_opened_tourney ?? 0,
        coinsGained: json.coins_gained_tourney ?? 0,
        deaths: json.deaths_tourney ?? 0,
        eggsThrown: json.egg_thrown_tourney ?? 0,
        farthestBowKill: json.longest_bow_kill_tourney ?? 0,
        farthestBowShot: json.longest_bow_shot_tourney ?? 0,
        fastestWin: json.fastest_win_tourney ?? 0,
        gamesPlayed: json.games_tourney ?? 0,
        highestKillGame: json.most_kills_game_tourney ?? 0,
        itemsEnchanted: json.items_enchanted_tourney ?? 0,
        kills: json.kills_tourney ?? 0,
        killstreak: json.killstreak_tourney ?? 0,
        losses: json.losses_tourney ?? 0,
        meleeKills: json.melee_kills_tourney ?? 0,
        mobKills: json.mob_kills_tourney ?? 0,
        pearlsThrown: json.enderpearls_thrown_tourney ?? 0,
        quits: json.quits_tourney ?? 0,
        survivedPlayers: json.survived_players_tourney ?? 0,
        timePlayed: json.time_played_tourney ?? 0,
        voidKills: json.void_kills_tourney ?? 0,
        wins: json.wins_tourney ?? 0,
        winstreak: json.winstreak_tourney ?? 0,
        wlr: cutOff((json.wins_tourney || 0) / (json.losses_tourney || 1)),
        kdr: cutOff((json.kills_tourney || 0) / (json.losses_tourney || 1)),
        bowRatio: cutOff((json.arrows_hit_tourney || 0) / (json.arrows_shot_tourney || 1))
      }
    },
    gamesPlayed: json.games ?? 0,
    halloweenBoxes: json.skywars_halloween_boxes ?? 0,
    harvestingSeason: json.harvesting_season ?? 0,
    headCollection: {
      prestigious: json.head_collection?.prestigious ?? [],
      recent: json.head_collection?.recent ?? []
    },
    headCount: {
      decent: json.heads_decent ?? 0,
      divine: json.heads_divine ?? 0,
      eww: json.heads_eww ?? 0,
      heavenly: json.heads_heavenly ?? 0,
      meh: json.heads_meh ?? 0,
      salty: json.heads_salty ?? 0,
      succulent: json.heads_succulent ?? 0,
      tasty: json.heads_tasty ?? 0,
      total: json.heads ?? 0,
      yucky: json.heads_yucky ?? 0
    },
    highestKillGame: json.most_kills_game ?? 0,
    itemsEnchanted: json.items_enchanted ?? 0,
    kills: json.kills ?? 0,
    killsWeeklyA: json.kills_weekly_a ?? 0,
    killsWeeklyB: json.kills_weekly_b ?? 0,
    killstreak: json.killstreak ?? 0,
    lastMode: json.lastMode ?? '',
    levelFormatted: json.levelFormatted ?? '',
    losses: json.losses ?? 0,
    meleeKills: json.melee_kills ?? 0,
    mobKills: json.mob_kills ?? 0,
    opals: json.opals ?? 0,
    packages: json.packages ?? [],
    paidSouls: json.paid_souls ?? 0,
    pearlsThrown: json.enderpearls_thrown ?? 0,
    privateGameSettings: {
      chestArmor: json.privategames?.chest_armour ?? '',
      chestBows: json.privategames?.chest_bows ?? '',
      chestSwords: json.privategames?.chest_swords ?? '',
      dragons: json.privategames?.dragons ?? '',
      enableLegacyItems: json.privategames?.enable_legacy_items ?? false,
      enableMaxKitsAndPerks: json.privategames?.enable_max_kits_and_perks ?? false,
      enableNightTime: json.privategames?.enable_night_time ?? false,
      enableTeleportMayhem: json.privategames?.enable_teleport_mayhem ?? false,
      healthBuff: json.privategames?.health_buff ?? '',
      lowGravity: json.privategames?.low_gravity ?? false,
      noKits: json.privategames?.no_kits ?? false,
      oneHitOneKill: json.privategames?.one_hit_one_kill ?? false,
      speed: json.privategames?.speed ?? ''
    },
    quits: json.quits ?? 0,
    recentChestHistory: json.chest_history_new ?? [],
    refillChestDestroy: json.refill_chest_destroy ?? 0,
    selectedPrestigeIcon: json.selected_prestige_icon ?? '',
    shards: json.shard ?? 0,
    skywarsChestHistory: json.skywars_chest_history ?? [],
    skywarsChests: json.skywars_chests ?? 0,
    skywarsChestsOpened: {
      commons: json.SkyWars_openedCommons ?? 0,
      epics: json.SkyWars_openedEpics ?? 0,
      legendaries: json.SkyWars_openedLegendaries ?? 0,
      rares: json.SkyWars_openedRares ?? 0,
      total: json.skywars_chests ?? 0
    },
    soulWellCount: json.soul_well ?? 0,
    soulWellLegendaries: json.soul_well_legendaries ?? 0,
    soulWellRares: json.soul_well_rares ?? 0,
    souls: json.souls ?? 0,
    soulsGathered: json.souls_gathered ?? 0,
    survivedPlayers: json.survived_players ?? 0,
    timePlayed: json.time_played ?? 0,
    usedSoulWell: json.usedSoulWell ?? false,
    voidKills: json.void_kills ?? 0,
    votes: {
      aegis: json.votes_Aegis ?? 0,
      agniTemple: json['votes_Agni Temple'] ?? 0,
      atuin: json.votes_Atuin ?? 0,
      birdhouse: json.votes_Birdhouse ?? 0,
      boomerang: json.votes_Boomerang ?? 0,
      canopy: json.votes_Canopy ?? 0,
      chronos: json.votes_Chronos ?? 0,
      coherence: json.votes_Coherence ?? 0,
      congo: json.votes_Congo ?? 0,
      courtyard: json.votes_Courtyard ?? 0,
      crumble: json.votes_Crumble ?? 0,
      dragonice: json.votes_Dragonice ?? 0,
      dwarfFortress: json['votes_Dwarf Fortress'] ?? 0,
      dwarven: json.votes_Dwarven ?? 0,
      eirene: json.votes_Eirene ?? 0,
      elven: json.votes_Elven ?? 0,
      entangled: json.votes_Entangled ?? 0,
      festiveTribute: json['votes_Festive Tribute'] ?? 0,
      firelinkShrine: json['votes_Firelink Shrine'] ?? 0,
      fortress: json.votes_Fortress ?? 0,
      fossil: json.votes_Fossil ?? 0,
      foundation: json.votes_Foundation ?? 0,
      frostbite: json.votes_Frostbite ?? 0,
      fungi: json.votes_Fungi ?? 0,
      generator: json.votes_Generator ?? 0,
      halloweenMemorial: json.votes_HalloweenMemorial ?? 0,
      haunted: json.votes_Haunted ?? 0,
      jinzhou: json.votes_Jinzhou ?? 0,
      longisland: json.votes_LongIsland ?? 0,
      magnus: json.votes_Magnus ?? 0,
      martian: json.votes_Martian ?? 0,
      megashire: json.votes_MegaShire ?? 0,
      memorial: json.votes_Memorial ?? 0,
      meteor: json.votes_Meteor ?? 0,
      mothership: json.votes_Mothership ?? 0,
      onionring: json.votes_Onionring ?? 0,
      onionringTwo: json['votes_Onionring 2'] ?? 0,
      overfall: json.votes_Overfall ?? 0,
      pitfall: json.votes_Pitfall ?? 0,
      plateau: json.votes_Plateau ?? 0,
      reef: json.votes_Reef ?? 0,
      rocky: json.votes_Rocky ?? 0,
      sanctum: json.votes_Sanctum ?? 0,
      sawmill: json.votes_Sawmill ?? 0,
      shattered: json.votes_Shattered ?? 0,
      shire: json.votes_Shire ?? 0,
      siege: json.votes_Siege ?? 0,
      skychurch: json.votes_Skychurch ?? 0,
      steampunk: json.votes_Steampunk ?? 0,
      strata: json.votes_Strata ?? 0,
      temple: json.votes_Temple ?? 0,
      toadstool: json.votes_Toadstool ?? 0,
      towers: json.votes_Towers ?? 0,
      tribal: json.votes_Tribal ?? 0,
      tribute: json.votes_Tribute ?? 0,
      tundra: json.votes_Tundra ?? 0,
      twistedGrove: json['votes_Twisted Grove'] ?? 0
    },
    wins: json.wins ?? 0,
    winstreak: json.winstreak ?? 0,
    xezbethLuck: json.xezbeth_luck ?? 0
  };
}
